sonar.projectKey=nereafalcon_POPBL6
sonar.organization=nereafalcon


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=POPBL6
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.projectName=POPBL6
sonar.projectVersion=1.0

# Incluye todo el código que quieres analizar
sonar.sources=PYTHON,FRONTEND,POPBL/chat/src,POPBL/paralelizacion/src

# Para Java Maven (detecta automáticamente, pero puedes indicarle dónde están)
sonar.java.binaries=POPBL/chat/target/classes,POPBL/paralelizacion/target/classes

# Excluir carpetas que no quieras analizar
#sonar.exclusions=**/node_modules/**,**/target/test-classes/**

# Lenguajes: si quieres, explícitalo
# sonar.language=java,js,python  # Nota: sonar.language está deprecated, mejor dejarlo para detectar automático

# Otras opciones específicas, si quieres
sonar.tests=
sonar.coverage.exclusions=**
