# Identificador único del proyecto en SonarQube
sonar.projectKey=POPBL6

# Nombre legible para el proyecto
sonar.projectName=POPBL6

# Versión del proyecto
sonar.projectVersion=1.0

# Directorio o carpetas con el código fuente a analizar
sonar.sources=.

# URL de SonarQube (local)
sonar.host.url=http://localhost:9000

# Aquí iría el token que generes en SonarQube (más abajo te digo cómo generarlo)
sonar.login=sqa_4eebf465573b27ce7b0c2559d4ec00e6424514d6
