name: SonarQube Analysis

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Ejecutar análisis SonarQube
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.projectKey=POPBL6
            -Dsonar.sources=POPBL/chat,POPBL/paralelizacion,PYTHON
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
